### ISSUE TITLE
Support Android 7

### ISSUE THREAD

**Issue by dassagichnicht** [fi3te/ILIASDownloaderAndroid#2]
Using the app with Android 7 causes some problem:

- trying to open the settings causes a crash of the app

- when you try to download files from ilias, the download isn't succesfull

It would be great if somebody knows how to fix this issues.
Thanks

**Comment by fi3te** [comment]
Hi dassagichnicht,

excuse my late reply!
The bug concerning the preference view is already fixed here but not published to the Play Store.

Regards,
Fiete

**Comment by dassagichnicht** [comment]
Thank You for your reply!
Yes, you are right, but the problem that the download isn't successfull unfortunally still exists.
